#### Exercise 1: Regression - Optimize

In [2]:
import keras
from keras.layers import Dense


model = keras.Sequential()
model.add(Dense(8, input_shape=(5,), activation= 'sigmoid'))
model.add(Dense(4, activation= 'sigmoid'))
model.add(Dense(1, activation= 'linear'))

model.compile(
  optimizer='adam',
  loss='mse',
  metrics=[keras.metrics.MeanAbsoluteError()] 
)

model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 8)                 48        
_________________________________________________________________
dense_4 (Dense)              (None, 4)                 36        
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 5         
Total params: 89
Trainable params: 89
Non-trainable params: 0
_________________________________________________________________


#### Exercise 2: Regression example

In [5]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import keras
from keras.layers import Dense

data= pd.read_csv('./data/auto-mpg.csv')

data.drop(['model year', 'origin', 'car name'], axis=1, inplace=True)

for col in data.columns:
  data[col]=pd.to_numeric(data[col], errors='coerce')

data.dropna(inplace=True)

X_train, X_test, y_train, y_test=train_test_split(data.drop('mpg', axis=1), data['mpg'], test_size=0.2, shuffle=False)

scaler=StandardScaler()
X_train= scaler.fit_transform(X_train)
X_test= scaler.transform(X_test)

print("Train")
print("\nX train shape : ", X_train.shape)
print("\nFirst 5 rows are:\n", X_train[:5])

print("\nThe train target : ")
print(y_train[:5].to_markdown())

print("\n\nTest\n")
print("X test shape : ", X_test.shape)
print("\nFirst 5 rows are:\n", X_test[:5])

print("\nThe test target : ")
print(y_test[:5].to_markdown())


#2

model= keras.Sequential(
    [
        Dense(15, input_shape=(X_train.shape[1],), activation='sigmoid'),
        Dense(10, activation='sigmoid'),
        Dense(1, activation='linear')
    ]
)

model.compile(
  optimizer='adam',
  loss='mse',
  metrics=[keras.metrics.MeanAbsoluteError()] 
)
model.fit(X_train, y_train, epochs=100, batch_size=5)

pred_test = model.predict(X_test)
print("\n Prediction\n", model.predict(X_test[:5]))

#print("\n Mean absolute error ", keras.metrics.MeanAbsoluteError()(y_test.to_numpy(), pred_test.reshape(1, -1)[0]))

mae= model.evaluate(X_test, y_test)[1]
print("Mean absolute error", mae)


Train

X train shape :  (313, 5)

First 5 rows are:
 [[ 1.28377043  0.88466635  0.4869698   0.45570808 -1.19481335]
 [ 1.28377043  1.28127292  1.36238071  0.67045896 -1.37736562]
 [ 1.28377043  0.98612384  0.98720461  0.37844321 -1.55991789]
 [ 1.28377043  0.85699612  0.98720461  0.37503446 -1.19481335]
 [ 1.28377043  0.8385493   0.7370872   0.39321443 -1.74247016]]

The train target : 
|    |   mpg |
|---:|------:|
|  0 |    18 |
|  1 |    15 |
|  2 |    18 |
|  3 |    16 |
|  4 |    17 |


Test

X test shape :  (79, 5)

First 5 rows are:
 [[-1.00254618 -0.55418542 -0.51349982 -0.1135522   1.76253341]
 [ 0.14061212  0.12834683 -0.51349982  0.31594957  1.25138706]
 [-1.00254618 -1.0522495  -0.81364071 -1.03959438  0.1925839 ]
 [-1.00254618 -0.71098337 -0.51349982 -0.44533664  0.08305253]
 [-1.00254618 -0.84011109 -0.88867593 -0.63736256  0.81326161]]

The test target : 
|     |   mpg |
|----:|------:|
| 315 |  24.3 |
| 316 |  19.1 |
| 317 |  34.3 |
| 318 |  29.8 |
| 319 |  31.3 |
Epoch

2024-10-23 17:51:07.803673: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2024-10-23 17:51:07.804141: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2499950000 Hz


63/63 [==============================] - 1s 7ms/step - loss: 495.3129 - mean_absolute_error: 21.2235
Epoch 2/100
63/63 [==============================] - 1s 12ms/step - loss: 477.3531 - mean_absolute_error: 20.9418
Epoch 3/100
63/63 [==============================] - 1s 11ms/step - loss: 451.6360 - mean_absolute_error: 20.2464
Epoch 4/100
63/63 [==============================] - 1s 10ms/step - loss: 427.7193 - mean_absolute_error: 19.6428
Epoch 5/100
63/63 [==============================] - 1s 10ms/step - loss: 410.0008 - mean_absolute_error: 19.1961
Epoch 6/100
63/63 [==============================] - 1s 8ms/step - loss: 366.1418 - mean_absolute_error: 17.9959
Epoch 7/100
63/63 [==============================] - 0s 7ms/step - loss: 375.6740 - mean_absolute_error: 18.1553
Epoch 8/100
63/63 [==============================] - 0s 6ms/step - loss: 373.3880 - mean_absolute_error: 17.9934
Epoch 9/100
63/63 [==============================] - 0s 5ms/step - loss: 321.5713 - mean_absolute_error:

#### Exercice 3 : Multi-classification - Softmax

In [6]:
model = keras.Sequential()
model.add(Dense(16, input_shape=(5,), activation= 'sigmoid'))
model.add(Dense(8, activation= 'sigmoid'))
model.add(Dense(5, activation= 'softmax'))
print(model.summary())

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_9 (Dense)              (None, 16)                96        
_________________________________________________________________
dense_10 (Dense)             (None, 8)                 136       
_________________________________________________________________
dense_11 (Dense)             (None, 5)                 45        
Total params: 277
Trainable params: 277
Non-trainable params: 0
_________________________________________________________________
None


#### Exercise 4: Multi classification - Optimize

In [7]:
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

#### Exercise 5: Multi classification example

In [ ]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelBinarizer
iris = datasets.load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state=1)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

#1
lb= LabelBinarizer()
y_train= lb.fit_transform(y_train)
y_test= lb.transform(y_test)
print("The first ten values of the train labels :\n",  y_train[:10])

#2
model= keras.Sequential(
    [
        Dense(16, input_shape=(X_train.shape[1],), activation='sigmoid'),
        Dense(len(y_train[0]), activation='softmax')
    ]
)
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

model.fit(X_train, y_train, epochs=100, batch_size=5)

print("Evaluate the accuracy: ",  model.evaluate(X_test, y_test)[1])
